# Generated by Django 4.1.3 on 2022-11-26 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NameOfTutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resources', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DjangoHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=500)),
                ('tags', models.CharField(max_length=100)),
                ('format', models.CharField(max_length=25)),
                ('difficulty', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=50, null=True)),
                ('time', models.CharField(choices=[('0-30 minutes', '0-30 minutes'), ('30 minutes - 1 hour', '30 minutes - 1 hour'), ('1-4 hours', '1-4 hours'), ('5-10 hours', '5-10 hours'), ('it takes days', 'it takes days')], max_length=50, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.nameoftutorial')),
            ],
        ),
    ]
