# Generated by Django 4.1.3 on 2022-11-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangohub',
            name='format',
            field=models.CharField(choices=[('Written', 'Written'), ('Video', 'Video')], max_length=50, null=True),
        ),
    ]
